version: "3.9"
services:
  rabbit_mq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  db:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
  vectorDb:
    image: ankane/pgvector
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=vector_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

